name: Firmware Build Test

on: [push]

jobs:
  Firmware-build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2020-01-13
    steps:
    - name: Checkout Firmware master
      uses: actions/checkout@v1
      with:
        repository: PX4/Firmware
        ref: master
        path: Firmware
        submodules: recurvise
    # - name: check_format
    #   env:
    #     CI: true
    #   run: make check_format
    # - name: main tests
    #   run: make tests
    # - name: Checkout submodules
    #   shell: bash
    #   run: |
    #     git submodule sync --recursive
    #     git submodule update --init --force --recursive
    - name: Configure Firmware to include current ECL version
      run: make #TODO
      # working-directory: Firmware

